FROM ruby:2.5.5

# Install dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs libev-dev

ENV RAILS_ROOT /var/www/app_name
RUN mkdir -p $RAILS_ROOT 
# Set working directory
WORKDIR $RAILS_ROOT
# Setting env up
ENV RAILS_ENV='production'
# ENV RACK_ENV='production'

# Adding gems
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock
RUN gem update --system 
ENV BUNDLER_VERSION 2.0.1
RUN gem install bundler && bundle config git.allow_insecure true && bundle install --jobs 20 --retry 5 

# Adding project files
COPY . .
# ENV SECRET_KEY_BASE="fb24e8c6a8f17b523d2247af8891ab12"
# Node.js
# RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - \
#     && apt-get install -y nodejs

# yarn
# RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -\
#     && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
#     && apt-get update \
#     && apt-get install -y yarn

# CMD [ "bash" ]
# RUN bundle exec rake db:create
# RUN bundle exec rake db:migrate
# RUN bundle exec rake db:seed
# RUN node --version
RUN bundle exec rake assets:precompile

EXPOSE 3000
CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]

