version: '3'
volumes:
  postgres: {}

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/DockerFile
    depends_on:
      - postgres
    ports:
      - 3000:3000
  postgres:
    env_file:
      - ".env"
    image: "postgres:11.0-alpine"
    volumes:
      - "postgres:/var/lib/postgresql/data"
  # web:
  #   build:
  #     context: .
  #     dockerfile: ./docker/web/DockerFile
  #   depends_on:
  #     - app
  #   ports:
  #     - 80:80
